import * as THREE from 'three';
import { ShapeType } from '../types/index';
export declare class SceneManager {
    private container;
    private scene;
    private camera;
    private renderer;
    private controls;
    private mainMesh;
    private isAutoRotating;
    private cameraMode;
    private rotationSpeed;
    private currentGeoType;
    private currentTexture;
    private camYaw;
    private camPitch;
    private isRecording;
    private transparentBackground;
    private stats;
    private matColor;
    private matRoughness;
    private matMetalness;
    private matWireframe;
    constructor(container: HTMLElement);
    private setupLights;
    createMesh(type: ShapeType): void;
    private createMaterial;
    private updatePolyCount;
    private animate;
    private applyCameraAngle;
    private handleResize;
    updateTexture(tex: THREE.Texture): void;
    setAutoRotate(enabled: boolean): void;
    toggleCameraLock(locked: boolean): void;
    setCameraMode(mode: 'turntable' | 'static'): void;
    setTransparentBg(enabled: boolean): void;
    setCameraAngle(yaw: number, pitch: number): void;
    setRotationSpeed(speed: number): void;
    resetCamera(): void;
    zoom(factor: number): void;
    exportGIF(delay: number): Promise<void>;
    takeSnapshot(): void;
    setMaterialColor(color: string): void;
    setMaterialRoughness(val: number): void;
    setMaterialMetalness(val: number): void;
    toggleWireframe(): boolean;
}
